#!/bin/bash
###########################################
#
# aptdate (v1.01)
# by just-another-user
#
# Description:
# Update system using apt
#
###########################################

clr='\033[0;33m'
clr2='\033[0;36m'
noclr='\033[0m'

echo -e ${clr}[APTDATE]${noclr} ${clr2}Removing cache${noclr}
sudo rm -rf /var/lib/apt/lists/*
sudo apt clean

echo -e ${clr}[APTDATE]${noclr} ${clr2}Updating repositories${noclr}
sudo apt -y update

echo -e ${clr}[APTDATE]${noclr} ${clr2}Upgrading available packages${noclr}
sudo apt -y dist-upgrade

echo -e ${clr}[APTDATE]${noclr} ${clr2}Fixing unmet dependencies${noclr}
sudo apt install -f -y

echo -e ${clr}[APTDATE]${noclr} ${clr2}Cleaning up...${noclr}
sudo apt -y autoremove

echo -e ${clr}[APTDATE]${noclr} ${clr2}Done :)${noclr}